# Identificação do projeto no SonarQube / SonarCloud
sonar.projectKey=Lucas21-10_sistema-academico-api
sonar.projectName=sistema-academico-api
sonar.projectVersion=1.0.0

# Organização (SonarQube Cloud / SonarCloud gratuito)
sonar.organization=lucas21-10

# Fontes e testes
sonar.sources=src,server.js
sonar.tests=tests
sonar.test.inclusions=tests/**/*.test.js

# Codificação
sonar.sourceEncoding=UTF-8

# Relatório de cobertura LCOV (gerado pelo Jest)
sonar.javascript.lcov.reportPaths=coverage/lcov.info

# Exclusões
sonar.exclusions=**/node_modules/**,coverage/**
sonar.coverage.exclusions=tests/**,node_modules/**

