name: Workflow de Commits

on:
  push:

jobs:
  qualidade:
    name: Job de Qualidade
    runs-on: ubuntu-latest

    steps:
      - name: Clonar repositório
        uses: actions/checkout@v4

      - name: Configurar Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'

      - name: Instalar dependências
        run: npm ci

      - name: Verificação de Linter
        run: npm run lint

      - name: Executar testes e cobertura de código
        run: npm test